version: '3.5'
services: 
    app:
        build: app
        environment: 
            CHOKIDAR_USEPOLLING: "true"
        volumes: 
            - ./app:/app
            - ./app/node_modules:/app/node_modules
        container_name: frontend_foton-challenge
        build: 
            context: ./app
        command: yarn start
        ports: 
            - "3000:3000"
